### PR TITLE
fix for GL_LINEAR

### PR DESCRIPTION
**Pull request by chaosfox**
Some time ago we disabled the GL_LINEAR and changed it to GL_NEAREST  because it was full of drawing artifacts(black lines, etc) that made the scaling look ugly but it worked.

Then a little after that @mrcdk added the "bilinear" option that made GL_LINEAR work but using frame buffer objects - not the best solution because it draws once off screen and then back to the screen.

Now I found a way to fix the GL_LINEAR but I would like it to be tested by everyone first to see if its working ok before merging.

Look for drawing artifacts or anything else that could be off. Also remember to use a resolution bigger than 800x600 because thats when GL_LINEAR is used.

### CODE REVIEW

**Comment by dtinth** [comment]
On Mac, there is little drawing artifacts, but with 800x600 resolution it works fine.

Screenshot

**Comment by chaosfox** [comment]
@dtinth what resolution is that on the screenshot ?

**Comment by keigen-shu** [comment]
It doesn't look like OGL is blending pixels that are over the boundary box defined in the XML. I painted the surrounding alphas with random pixel noise, but the effect is not seen here.
http://www.postimg.com/image/92000/2012-11-21-193220_1366x768_scrot-91888.jpg

This is running at 9001 \* 9001 (my screen is 1366*768)

**Comment by chaosfox** [comment]
can you substitute the TextureLoader.getNextPOT for this https://gist.github.com/4124542 and see if this resolves the problem ?

**Comment by dtinth** [comment]
My resolution is 1152x720, and yes, it worked.

yay

**Comment by chaosfox** [comment]
nice, but just one more test, I think I got it to work without giving up on the power of 2 textures.
can you guys test this one please https://gist.github.com/4124759, just substitute the entire TextureLoader class for it.

**Comment by dtinth** [comment]
Still works on both 1152x720 and 1680x1080.

**Comment by chaosfox** [comment]
@dtinth nice, i think everything is alright now.
@keigen-shu could you test this last one just to be sure everything is working ? thanks.

**Comment by keigen-shu** [comment]
It looks perfect on practical sizes.

9001 \* 9001 looks great now.  http://postimg.com/93000/2012-11-22-230706_1366x768_scrot-92105.jpg
There are still some weird stuff though ( I think it's my driver ), like this 1px shrink on the left side of the lifebar. http://postimg.com/93000/2012-11-22-231349_1366x768_scrot-92106.jpg

This is also slightly visible when I use 2400 \* 1800 (3:3 scale). I don't have a screenshot because all image hosting sites I know convert to jpg which blurs out the detail.

**Comment by chaosfox** [comment]
nice, I'm going to merge this then.

**Pull request merged**
