### PR TITLE
Open a LWJGL window in a separate thread when assigning keys

### PR DESCRIPTION
**Pull request by dtinth**
On Mac OS X, in configuration screen, the game crashes when I try to change the keyboard bindings, so I created a new thread for the LWJGL window and that fixed it.

@chaosfox, @mrcdk, could you check if it still works on Windows/Linux or not?

### CODE REVIEW

**Comment by keigen-shu** [comment]
It now works on Arch Linux. Before this, pressing anything didn't change the key binding.

```
$ java -version
java version "1.7.0_09"
OpenJDK Runtime Environment (IcedTea7 2.3.3) (ArchLinux build 7.u9_2.3.3-1-x86_64)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)
```

**Comment by chaosfox** [comment]
works for me too, before and after the change.

the only thing I would change is to add a thread.join after the thread.start to block the user from clicking around the interface while that window is open, ideally we would use a modal dialog for this but the lwjgl window can't do this.

**Comment by dtinth** [comment]
I tried `thread.join()`, but it doesn't work.

Seems like on Mac it relies on AWT to handle keyboard press and other stuff. By blocking the UI thread, the keyboard setting windows couldn't get the keyboard input data. :(

**Comment by chaosfox** [comment]
I see.. then instead of thread.join you could disable the frame with this.setEnable(false);, the problem is re-enabling it after the thread ends -- I'm not sure if it will work if you call setEnable from inside the thread.

edit: look into RenderThread - -thats exactly what we do for the render.

**Comment by dtinth** [comment]
Ok, disabled the frame on opening the dialog, and re-enabled it.

**Comment by chaosfox** [comment]
this works fine for me. you can go ahead and merge, unless you are waiting for something ?

**Pull request merged**
